### ISSUE TITLE
Retain information about its network peer

### ISSUE THREAD

**Issue by lzap** [lzap/pcp-mmvstatsd#1]
Put remote IP address (or hostname) as part of the PCP namespace.

**Comment by natoscott** [comment]
See the metric namespace naming requirements in the pmns(4) man page 'SYNTAX' section - metric instance domains is a better suited place for this sort of thing.

**Comment by lzap** [comment]
"You're gonna have a bad time if you try to put hostnames or IP addresses in the (dot-separated) PCP namespace - see the metric namespace naming requirements in the pmns(4) man page 'SYNTAX' section. Metric instance domains is a much better suited place for that sort of thing."
